<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '企业简介';
$typeArr[3] = '企业文化';
$typeArr[4] = '发展历程';
$typeArr[5] = '新闻资讯';
$typeArr[6] = '公司新闻';
$typeArr[7] = '行业新闻';
$typeArr[8] = '产品中心';
$typeArr[9] = '产品一类';
$typeArr[10] = '产品二类';
$typeArr[11] = '产品三类';
$typeArr[12] = '产品四类';
$typeArr[13] = '服务支持';
$typeArr[14] = '售后服务';
$typeArr[15] = '合作流程';
$typeArr[16] = '联系我们';
$typeArr[18] = '在线留言';
$typeArr[17] = '联系方式';
$typeArr[19] = '幻灯片';
?>