<?php
$z[0]=Array("arcurl","",69,84);
$z[1]=Array("title","",93,107);
$z[2]=Array("litpic","",135,150);
$z[3]=Array("title","",182,196);
$z[4]=Array("arcurl","",293,308);
$z[5]=Array("title","",317,331);
$z[6]=Array("title","",349,363);
$z[7]=Array("pubdate","",396,448);
$z[7][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[8]=Array("description","",520,570);
$z[8][4]['function']="cn_substr(@me,100)";

?>