<li class="clearfix">
              <div class="s-newsnrl"><a href="[field:arcurl/]" title="[field:title/]" target="_blank"><img src="[field:litpic/]" width="200" height="110" alt="[field:title/]" /><span></span></a></div>
              <div class="s-newsnrr">
                <h3><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h3>
                <span>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span>
                <div class="s-newsfoot">
                  <p>[field:description function='cn_substr(@me,100)'/]...</p>
                </div>
              </div>
            </li>