<div class="s-yyczr">
        <div class="s-yyczimg"><a href="[field:arcurl/]" title="[field:title/]" target="_blank"><img src="[field:litpic/]" width="444" height="302" alt="[field:title/]" /></a></div>
        <div class="s-yycznews">
          <h3><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h3>
          <p>[field:description function='cn_substr(@me,140)'/]...</p>
        </div>
      </div>