<dd class="active ">
                            <div alt="" data-otherlink="0" data-phref="view.php?aid=[field:id/]" class="productatag">
                              <div class="imgWrap"><a href="view.php?aid=[field:id/]"><img src="[field:litpic/]"></a></div>
                              <div class="infoWrap">
                                <h3 class="productTitle"><span class="name "><a href="view.php?aid=[field:id/]">[field:title/]</a> </span></h3>
                                <p class="mark"> </p>
                              </div>
                            </div>
                          </dd>