<?php
$z[0]=Array("pubdate","",119,165);
$z[0][4]['function']="strftime(\"%d\",@me)";
$z[1]=Array("pubdate","",194,243);
$z[1][4]['function']="strftime(\"%Y-%m\",@me)";
$z[2]=Array("arcurl","",348,363);
$z[3]=Array("title","",372,386);
$z[4]=Array("title","",416,430);
$z[5]=Array("arcurl","",470,485);
$z[6]=Array("title","",494,508);
$z[7]=Array("description","",532,582);
$z[7][4]['function']="cn_substr(@me,150)";

?>