<li>
                <div class="s-newsbj">
                  <div class="time">
                    <p class="day">[field:pubdate function='strftime("%d",@me)'/]</p>
                    <p>[field:pubdate function='strftime("%Y-%m",@me)'/]</p>
                  </div>
                  <div class="intro">
                    <h3> <a href="[field:arcurl/]" title="[field:title/]" target="_blank" class="tit">[field:title/]</a></h3>
                    <a href="[field:arcurl/]" title="[field:title/]" target="_blank">　　[field:description function='cn_substr(@me,150)'/]...</a> </div>
                </div>
                <div class="s-dbyy"></div>
              </li>