<div class="new">
        <div class="new-pic"><a href="[field:arcurl/]"><img src="[field:litpic/]" alt="[field:title/]"></a></div>
        <div class="new-txt">
          <h3><a href="[field:arcurl/]">[field:title/]</a></h3>
          <span>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span>
          <p>[field:description function='cn_substr(@me,250)'/]...</p>
          <a href="[field:arcurl/]">查看详情 ></a> </div>
      </div>