<?php
$z[0]=Array("field","",109,128);
$z[0][4]['name']="title";
$z[1]=Array("global","",129,155);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",196,225);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",265,323);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1789,1826);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("include","",1901,1940);
$z[5][4]['filename']="banner_m.htm";
$z[6]=Array("channel","\r\n                    <li class=\"z3g-column2 pro_bull\" style=\" margin-left:2%;width:46%; margin-bottom:10px; float:left; display:block;\"> <a href=\"list.php?tid=[field:id/]\">[field:typename/]</a> </li>\r\n                    ",2730,2992);
$z[6][4]['type']="son";
$z[7]=Array("field","",4325,4346);
$z[7][4]['name']="content";
$z[8]=Array("include","",4854,4891);
$z[8][4]['filename']="foot_m.htm";

?>