<?php
$z[0]=Array("pubdate","",89,135);
$z[0][4]['function']="strftime(\"%d\",@me)";
$z[1]=Array("pubdate","",165,214);
$z[1][4]['function']="strftime(\"%Y-%m\",@me)";
$z[2]=Array("arcurl","",319,334);
$z[3]=Array("title","",343,357);
$z[4]=Array("title","",387,401);
$z[5]=Array("arcurl","",441,456);
$z[6]=Array("title","",465,479);
$z[7]=Array("description","",497,547);
$z[7][4]['function']="cn_substr(@me,140)";

?>