<li class="clearfix">
              <div class="s-newsnrl"><a href="[field:arcurl/]" title="[field:title/]" target="_blank"><img src="[field:litpic/]" width="200" height="110" alt="[field:title/]" /><span></span></a></div>
              <div class="s-newsnrr">
                <h3><a href="[field:arcurl/]" title="[field:title/]" target="_blank">[field:title/]</a></h3>
                <span>[field:pubdate function='strftime("%Y-%m-%d",@me)'/]</span>
                <div class="s-newsfoot">
                  <p>[field:description function='cn_substr(@me,50)'/]...</p>
                </div>
              </div>
            </li>
			{/dede:list}

          </ul>
        </div>
        <div class="clear"></div>
        <div class="news-change"></div>
      </div>
    </div>
    <div class="s-yycz clearfix">
      <div class="s-aboutbt">
        <h2><a class="s-yyczbt" href="/zhishi/" target="_blank">营养知识</a></h2>
        <div class="s-ggby"> <a href="/zhishi/yingyangkecheng/" target="_blank">营养课程</a>
          <a href="/zhishi/jiankangyinshi/" target="_blank">健康饮食</a>
          <a href="/zhishi/fengfucanzhuo/" target="_blank">丰富餐桌</a>
          <a href="/zhishi/youzhiroupin/" target="_blank">优质肉品</a> </div>
      </div>
      <div class="s-yyczl">
        <div class="news-list sy-news-list">
          <div class="list sy-list">
            <div class="news-move">
              <ul>
                <li class="">
                  <div class="time">
                    <p class="day"> 22</p>
                    <p> 2016-04</p>
                  </div>
                  <div class="intro">
                    <h3> <a href="/zhishi/jiankangyinshi/45.html" title="夏季吃下龙虾的原则" target="_blank" class="tit">夏季吃下龙虾的原则</a></h3>
                    <a href="/zhishi/jiankangyinshi/45.html" title="夏季吃下龙虾的原则" target="_blank">在夏季现代人们最喜欢的就是在大排档里点几个小菜喝点小酒了，当热小龙虾这道菜也是餐桌上的主菜之一，可是你知道在夏...</a> </div>
                </li>
<li class="">
                  <div class="time">
                    <p class="day"> 20</p>
                    <p> 2015-07</p>
                  </div>
                  <div class="intro">
                    <h3> <a href="/zhishi/yingyangkecheng/7.html" title="爆炒羊肉营养次之" target="_blank" class="tit">爆炒羊肉营养次之</a></h3>
                    <a href="/zhishi/yingyangkecheng/7.html" title="爆炒羊肉营养次之" target="_blank">爆炒羊肉营养次之 爆法通常以葱爆羊肉为代表。爆是指将牛羊肉放入锅中旺火急炒的一种烹调术。此菜由昔日的铛炮羊肉演...</a> </div>
                </li>
<li class="">
                  <div class="time">
                    <p class="day"> 20</p>
                    <p> 2015-07</p>
                  </div>
                  <div class="intro">
                    <h3> <a href="/zhishi/yingyangkecheng/5.html" title="烤、炸羊肉油分大，营养损失最多" target="_blank" class="tit">烤、炸羊肉油分大，营养损失最多</a></h3>
                    <a href="/zhishi/yingyangkecheng/5.html" title="烤、炸羊肉油分大，营养损失最多" target="_blank">烤肉应选用鲜嫩的后腿和上脑部位，剔除筋膜，压去水分，切成薄片。如果切得厚薄不匀，或筋膜剔得不干净，吃时会有腥膻...</a> </div>
                </li>

              </ul>
            </div>
          </div>
        </div>
      </div>
      <div class="s-yyczr">
        <div class="s-yyczimg"><a href="/zhishi/jiankangyinshi/45.html" title="夏季吃下龙虾的原则" target="_blank"><img src="/uploads/allimg/150817/1-150QF94K50-L.jpg" width="444" height="302" alt="夏季吃下龙虾的原则" /></a></div>
        <div class="s-yycznews">
          <h3><a href="/zhishi/jiankangyinshi/45.html" title="夏季吃下龙虾的原则" target="_blank">夏季吃下龙虾的原则</a></h3>
          <p>在夏季现代人们最喜欢的就是在大排档里点几个小菜喝点小酒了，当热小龙虾这道菜也是餐桌上的主菜之一，可是你知道在夏...</p>
        </div>
      </div>
 </div>
  </div>
</div>
<!--中间结束--> 
<!--底部开始--> 
{dede:include filename="foot.htm"