<li><a href="[field:arcurl/]" title="[field:title/]" target="_blank"><img src="[field:litpic/]" width="268" height="268" alt="[field:title/]"/></a>
            <div class="s-yccpbt"> <a href="[field:arcurl/]" title="[field:title/]" target="_blank">
              <h3>[field:title/]</h3>
              <p>[field:description function='cn_substr(@me,250)'/]...</p>
              </a> </div>
          </li>