<?php
$z[0]=Array("pagestyle","",0,91);
$z[0][4]['maxwidth']="800";
$z[0][4]['pagepicnum']="12";
$z[0][4]['ddmaxwidth']="200";
$z[0][4]['row']="3";
$z[0][4]['col']="4";
$z[0][4]['value']="2";
$z[1]=Array("img"," /uploads/allimg/160503/1-160503161U2.jpg ",93,259);
$z[1][4]['ddimg']="/uploads/allimg/160503/1-160503161U2.jpg";
$z[1][4]['text']="十四号产品展示";
$z[1][4]['width']="355";
$z[1][4]['height']="355";
$z[2]=Array("img"," /uploads/allimg/160503/1-160503161U2-50.jpg ",261,433);
$z[2][4]['ddimg']="/uploads/allimg/160503/1-160503161U2-50.jpg";
$z[2][4]['text']="十四号产品展示";
$z[2][4]['width']="355";
$z[2][4]['height']="355";
$z[3]=Array("img"," /uploads/allimg/160503/1-160503161U2-51.jpg ",435,607);
$z[3][4]['ddimg']="/uploads/allimg/160503/1-160503161U2-51.jpg";
$z[3][4]['text']="十四号产品展示";
$z[3][4]['width']="355";
$z[3][4]['height']="355";
$z[4]=Array("img"," /uploads/allimg/160503/1-160503161U2-52.jpg ",609,781);
$z[4][4]['ddimg']="/uploads/allimg/160503/1-160503161U2-52.jpg";
$z[4][4]['text']="十四号产品展示";
$z[4][4]['width']="355";
$z[4][4]['height']="355";

?>