<?php
$z[0]=Array("global","",132,153);
$z[0][4]['name']="cfg_dh";
$z[1]=Array("global","",233,254);
$z[1][4]['name']="cfg_qq";
$z[2]=Array("type","<a href=\"[field:typelink /]\"><b class=\"f\"></b>在线留言</a>",346,443);
$z[2][4]['typeid']="18";
$z[3]=Array("flink","<span>[field:link /]</span>",576,637);
$z[3][4]['row']="24";
$z[4]=Array("global","",773,794);
$z[4][4]['name']="cfg_mc";
$z[5]=Array("channelartlist","\r\n        <li>\r\n          <p>{dede:field name='typename'/}</p>\r\n          <ol class=\"in-nav\">\r\n            {dede:channel type='son' noself='yes'}\r\n            <li> <a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ol>\r\n        </li>\r\n        ",1179,1530);
$z[5][4]['row']="6";
$z[5][4]['typeid']="top";
$z[6]=Array("global","",1583,1609);
$z[6][4]['name']="cfg_powerby";
$z[7]=Array("global","",1665,1689);
$z[7][4]['name']="cfg_beian";

?>