<?php
$z[0]=Array("global","",153,179);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("field","(@me==\"\")? @me=\" class='hover'\":@me=\"\";",827,916);
$z[1][4]['name']="typeid";
$z[1][4]['runphp']="yes";
$z[2]=Array("channelartlist","\r\n        <li> <a {dede:field name='currentstyle'/} href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\r\n          <ol class=\"in-nav\">\r\n            {dede:channel type='son' noself='yes'}\r\n            <li> <a href=\"[field:typelink/]\">[field:typename/]</a></li>\r\n            {/dede:channel}\r\n          </ol>\r\n        </li>\r\n        ",944,1354);
$z[2][4]['row']="6";
$z[2][4]['typeid']="top";

?>