<?php
$z[0]=Array("channel","\r\n      <div class=\"sid-item\">\r\n        <h3><a href=\"[field:typeurl/]\">[field:typename/]</a></h3>\r\n      </div>\r\n      ",45,204);
$z[0][4]['type']="son";
$z[1]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"></a>\r\n            <p>[field:title/]</p>\r\n          </li>\r\n          ",401,621);
$z[1][4]['row']="5";
$z[1][4]['titlelen']="36";
$z[1][4]['typeid']="8";

?>