<?php
$z[0]=Array("field","",229,248);
$z[0][4]['name']="title";
$z[1]=Array("global","",249,275);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",316,345);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",385,443);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",905,941);
$z[4][4]['filename']="nav_m.htm";
$z[5]=Array("include","",967,1004);
$z[5][4]['filename']="head_m.htm";
$z[6]=Array("list","\r\n      <li> <a href=\"view.php?aid=[field:id/]\"> <img src=\"[field:litpic/]\" alt=\"[field:title/]\">\r\n        <p class=\"title\">[field:title/]</p>\r\n        <span class=\"title bg\"></span> </a> </li>\r\n      ",1077,1328);
$z[6][4]['pagesize']="9";
$z[6][4]['titlelen']="36";
$z[7]=Array("pagelist","",1428,1484);
$z[7][4]['listitem']="pre,next,pageno";
$z[7][4]['listsize']="3";
$z[8]=Array("include","",1569,1606);
$z[8][4]['filename']="foot_m.htm";

?>