<?php
$z[0]=Array("field","",109,128);
$z[0][4]['name']="title";
$z[1]=Array("global","",129,155);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",196,225);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",265,323);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1789,1826);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("include","",1893,1932);
$z[5][4]['filename']="banner_m.htm";
$z[6]=Array("channel","\r\n                    <li class=\"z3g-column2 pro_bull\" style=\" margin-left:2%;width:46%; margin-bottom:10px; float:left; display:block;\"> <a href=\"list.php?tid=[field:id/]\">[field:typename/]</a> </li>\r\n                    ",2713,2975);
$z[6][4]['type']="son";
$z[7]=Array("list","\r\n                <dd class=\"active \">\r\n                  <div alt=\"\" data-otherlink=\"0\" data-phref=\"view.php?aid=[field:id/]\" class=\"productatag\">\r\n                    <div class=\"imgWrap\"><a href=\"view.php?aid=[field:id/]\"><img src=\"[field:litpic/] \"></a></div>\r\n                    <div class=\"infoWrap\">\r\n                      <h3 class=\"productTitle\"><span class=\"name \"><a href=\"view.php?aid=[field:id/]\">[field:title/]</a> </span></h3>\r\n                      <p class=\"mark\"> </p>\r\n                    </div>\r\n                  </div>\r\n                </dd>\r\n                ",4252,4884);
$z[7][4]['pagesize']="6";
$z[7][4]['titlelen']="36";
$z[8]=Array("pagelist","",5068,5124);
$z[8][4]['listitem']="pre,next,pageno";
$z[8][4]['listsize']="5";

?>