<?php
$z[0]=Array("field","",342,361);
$z[0][4]['name']="title";
$z[1]=Array("global","",362,388);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",429,458);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",498,556);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",901,937);
$z[4][4]['filename']="nav_m.htm";
$z[5]=Array("include","",965,1002);
$z[5][4]['filename']="head_m.htm";
$z[6]=Array("list","\r\n    <li> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">[field:title/]<span class=\"fr\">[field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/] </span></a> </li>\r\n    ",1042,1269);
$z[6][4]['pagesize']="10";
$z[6][4]['titlelen']="36";
$z[7]=Array("pagelist","",1389,1445);
$z[7][4]['listitem']="pre,next,pageno";
$z[7][4]['listsize']="3";
$z[8]=Array("include","",1538,1575);
$z[8][4]['filename']="foot_m.htm";

?>