<?php
$z[0]=Array("field","",109,128);
$z[0][4]['name']="title";
$z[1]=Array("global","",129,155);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",196,225);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",265,323);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1725,1762);
$z[4][4]['filename']="head_m.htm";
$z[5]=Array("include","",1830,1869);
$z[5][4]['filename']="banner_m.htm";
$z[6]=Array("channel","\r\n                    <li class=\"z3g-column2 pro_bull\" style=\" margin-left:2%;width:46%; margin-bottom:10px; float:left; display:block;\"> <a href=\"list.php?tid=[field:id/]\">[field:typename/]</a> </li>\r\n                    ",2661,2923);
$z[6][4]['type']="son";
$z[7]=Array("list","\r\n              <li class=\"active\"> <a href=\"view.php?aid=[field:id/]\" title=\"[field:title/]\">\r\n                <div class=\"js_gotoNewsDetail\" data-id=\"143\">\r\n                  <h3 class=\"newsTitle\"> <em class=\"icon\"></em> <span class=\"name\"> [field:title/] </span> </h3>\r\n                  <p class=\"time\"> [field:pubdate function='strftime(\"%Y-%m-%d\",@me)'/] </p>\r\n                </div>\r\n                </a> </li>\r\n              ",4088,4572);
$z[7][4]['pagesize']="10";
$z[7][4]['titlelen']="36";
$z[8]=Array("pagelist","",4696,4752);
$z[8][4]['listitem']="pre,next,pageno";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",4854,4891);
$z[9][4]['filename']="foot_m.htm";

?>