<?php
$z[0]=Array("field","",287,306);
$z[0][4]['name']="title";
$z[1]=Array("global","",307,333);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",374,396);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",436,487);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",1232,1268);
$z[4][4]['filename']="nav_m.htm";
$z[5]=Array("include","",1293,1330);
$z[5][4]['filename']="head_m.htm";
$z[6]=Array("include","",2411,2448);
$z[6][4]['filename']="foot_m.htm";

?>